# Setup
title:               medotkato
tagline:             'Череп не жмёт'
description:         'Камерный блог прикладных размышлений о том, как глубже думать и легче делать дела. Пишу не часто, но, как правило, что-то полезное.'
url:                 https://medotkato.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              medotkato
  url:               https://github.com/medotkato
  email:             medotkato@yandex.ru

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: UA-168017419-1
