# Setup
title:               medotkato
tagline:             'Череп не жмёт'
description:         'Камерный блог прикладных размышлений о происходящем и бизнесе (и даже иногда об IT-бизнесе). Пишу не часто, но, как правило, по делу.'
url:                 https://medotkato.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              medotkato
  url:               https://github.com/medotkato
  email:             medotkato@yandex.ru

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-168017419-1
